/**
 * An individual setting for a vehicle/user pair
 * Stores the value as well as the epoch time of the last change. The epoch is used to compare with remote values and determine which one is newer.
 */
export type CockpitSetting = {
  /**
   * The epoch time of the setting
   */
  epochLastChangedLocally: number
  /**
   * The value of the setting
   */
  value: any
}

export type SettingsPackage = Record<string, CockpitSetting>

/**
 * UserSettings is a map with the settings of different vehicles for a single user.
 * The keys are the vehicle ids and the values are the settings for that vehicle.
 * It's how the settings are stored on the top-side device (Cockpit).
 */
export interface UserSettings {
  [key: string]: SettingsPackage
}

/**
 * VehicleSettings is a map with the settings of different users for a single vehicle.
 * The keys are the user ids and the values are the settings for that user.
 * It's how the settings are stored on the vehicle.
 */
export interface VehicleSettings {
  [key: string]: SettingsPackage
}

/**
 * LocalSyncedSettings is a map with the settings for different users.
 * The keys are the user ids and the values are the user settings.
 */
export interface LocalSyncedSettings {
  /**
   * The settings for different users
   */
  [key: string]: UserSettings
}

/**
 * OldCockpitSetting is the type of the settings before the settings manager was introduced.
 */
export type OldCockpitSetting = any

export type OldCockpitSettingsPackage = Record<string, OldCockpitSetting>

/**
 * SettingsListener is the type of the listener for the settings manager.
 */
export type SettingsListener = (newSetting: CockpitSetting) => void

/**
 * SettingsListeners is a map with the listeners for the settings manager.
 * The keys are the keys of the settings and the values are the listeners for that setting.
 */
export type SettingsListeners = Record<
  string,
  {
    /**
     * The id of the listener
     * Generated by the settings manager
     * Used to unregister the listener
     */
    id: string
    /**
     * The callback of the listener
     */
    callback: SettingsListener
  }[]
>

/**
 * A queue of key value updates for a vehicle
 * Only the most recent change is stored for each vehicle/user/key combination
 */
export interface KeyValueVehicleUpdateQueue {
  [vehicleId: string]: {
    [userId: string]: {
      [key: string]: {
        /**
         * The new value of the setting
         */
        value: any
        /**
         * The epoch to be written to the setting
         */
        epochChange: number
      }
    }
  }
}

/**
 * VehicleOnlineEvent is the type of the event for when a vehicle comes online.
 */
export type VehicleOnlineEvent = CustomEvent<{
  /**
   * The address of the vehicle that came online
   */
  vehicleAddress: string
}>

/**
 * UserChangedEvent is the type of the event for when a user changes.
 */
export type UserChangedEvent = CustomEvent<{
  /**
   * The username of the user that changed
   */
  username: string
}>

/**
 * Define the custom event types for the settings management
 */
declare global {
  /**
   * Custom event types for the window object
   */
  interface WindowEventMap {
    /**
     * Event triggered when a vehicle comes online
     */
    // eslint-disable-next-line jsdoc/require-jsdoc
    'vehicle-online': VehicleOnlineEvent
    /**
     * Event triggered when the user changes
     */
    // eslint-disable-next-line jsdoc/require-jsdoc
    'user-changed': UserChangedEvent
  }
}

/**
 * NoVehicleIdErrorName is the name of the error for when a vehicle ID is not found.
 */
export const NoVehicleIdErrorName = 'NoVehicleIdError'

/**
 * The reason a sync operation was triggered
 */
export type SyncReason = 'vehicle-online' | 'user-changed'

/**
 * How a setting was resolved during the merge between local and vehicle
 */
export type SyncSettingResolution = 'from-vehicle' | 'from-local' | 'same' | 'new-on-vehicle' | 'new-on-local'

/**
 * Details about how an individual setting was resolved during sync
 */
export interface SyncSettingDetail {
  /**
   * The setting key
   */
  key: string
  /**
   * How the setting was resolved
   */
  resolution: SyncSettingResolution
}

/**
 * Discriminated union of all sync status events emitted by the SettingsManager
 */
export type SyncStatusEvent =
  | {
      /**
       * The reason the sync was started
       */
      type: 'sync-started'
      /**
       * The username of the user that triggered the sync
       */
      reason: SyncReason
      /**
       * The ID of the vehicle that triggered the sync
       */
      user: string
      /**
       *
       */
      vehicleId: string
    }
  | {
      /**
       * The current step of the sync
       */
      type: 'sync-step'
      /**
       * The setting was resolved
       */
      step: string
    }
  | {
      /**
       * The sync started
       */
      type: 'setting-resolved'
      /**
       * The key of the setting that was pushed
       */
      detail: SyncSettingDetail
    }
  | {
      /**
       *
       */
      type: 'push-started'
      /**
       * The number of keys that were pushed
       */
      totalKeys: number
    }
  | {
      /**
       * The number of keys that were skipped while pushing
       */
      type: 'push-progress'
      /**
       * The key of the setting that was skipped
       */
      key: string
      /**
       * The number of keys that were pushed
       */
      pushed: number
      /**
       * The number of keys that were skipped while pushing
       */
      skipped: number
      /**
       * The total number of keys that were pushed
       */
      total: number
    }
  | {
      /**
       * The key that was skipped
       */
      type: 'push-skipped'
      /**
       * The error that occurred while pushing the setting
       */
      key: string
      /**
       * The reason the push was skipped
       */
      reason: string
    }
  | {
      /**
       * The sync completed successfully
       */
      type: 'sync-completed'
    }
  | {
      /**
       * The sync was aborted
       */
      type: 'sync-aborted'
      /**
       * The reason the sync was aborted
       */
      reason: string
    }
  | {
      /**
       * The sync failed
       */
      type: 'sync-error'
      /**
       * The error that occurred while syncing
       */
      error: string
    }
  | {
      /**
       * The key that was pushed to the vehicle
       */
      type: 'key-pushed'
      /**
       * The key that was pushed to the vehicle
       */
      key: string
      /**
       * The username of the user that pushed the setting
       */
      user: string
      /**
       * The ID of the vehicle that the setting was pushed to
       */
      vehicleId: string
    }

/**
 * Callback type for sync status listeners
 */
export type SyncStatusListener = (event: SyncStatusEvent) => void
